#!/usr/bin/env node
/**
 * Downloads self-hosted webfonts and generates src/styles/fonts.css.
 *
 * Why self-hosted: otogidb previously relied on Cloudflare Fonts, which rewrites
 * the Google Fonts <link> at the edge to same-origin /cf-fonts/ paths. That works,
 * but it is a dashboard toggle nothing in the repo asserts, and Cloudflare documents
 * that unsupported pages "gracefully fallback to using Google Fonts" - which would
 * silently start sending visitor IPs to Google again. Adding a CSP would trigger
 * exactly that. Hosting the files ourselves removes the dependency, and also takes
 * ~460KB of injected @font-face CSS out of every page's HTML.
 *
 * Source is Google Fonts, not /cf-fonts/. Once the Google <link> is removed,
 * Cloudflare stops rewriting and those /cf-fonts/ URLs cease to exist, so sourcing
 * from them would make this script a one-shot. This runs on a developer machine at
 * build time - no visitor ever contacts Google.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile, readdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FONT_DIR = path.resolve(__dirname, '../src/styles/fonts');
const CSS_OUT = path.resolve(__dirname, '../src/styles/fonts.css');

// A modern UA is required or Google serves legacy TTF instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/**
 * Noto Serif JP is deliberately absent. It only ever appeared as a fallback behind
 * Reggae One on `.site-logo` and `header .link`, whose text is "OtogiDB", "Cards",
 * "Calendar", "Updates", "Blog", "Tools" - all ASCII. It never rendered a glyph,
 * and cost 124 files.
 */
const FAMILIES = [
  {
    // Variable (wght axis): one file per subset covers 400-700.
    css: 'Inter:wght@400;500;600;700',
    slug: 'inter',
  },
  {
    // Variable (wght axis): 124 files cover all three weights.
    // The CJK subsets are the reason this is worth keeping - Japanese card names
    // appear throughout the site's body text.
    css: 'Noto+Sans+JP:wght@400;500;700',
    slug: 'noto-sans-jp',
  },
  {
    // Latin slice ONLY. Reggae One styles the logo and nav links, which are ASCII.
    // Its other 122 CJK slices are dead weight.
    css: 'Reggae+One',
    slug: 'reggae-one',
    latinOnly: true,
  },
];

const BASIC_LATIN = 'U+0000-00FF';

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

/** Parse @font-face blocks out of a Google Fonts stylesheet. */
function parseFaces(css) {
  return [...css.matchAll(/@font-face\s*\{([^}]*)\}/g)].map((m) => {
    const body = m[1];
    const pick = (re) => (body.match(re) || [, ''])[1].trim();
    return {
      family: pick(/font-family:\s*([^;]+);/).replace(/['"]/g, ''),
      style: pick(/font-style:\s*([^;]+);/) || 'normal',
      weight: pick(/font-weight:\s*([^;]+);/) || '400',
      url: pick(/src:\s*url\(([^)]+)\)/),
      range: pick(/unicode-range:\s*([^;]+);/),
    };
  });
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });

  // Start clean so removed subsets don't linger as orphans.
  if (existsSync(FONT_DIR)) {
    for (const f of await readdir(FONT_DIR)) {
      if (f.endsWith('.woff2')) await rm(path.join(FONT_DIR, f));
    }
  }

  const chunks = [
    '/* GENERATED by scripts/fetch-fonts.mjs - do not edit by hand.',
    ' * Re-run that script to regenerate. See its header for why fonts are self-hosted.',
    ' */',
    '',
  ];
  const downloads = new Map(); // local filename -> remote url
  let totalFaces = 0;

  for (const fam of FAMILIES) {
    const css = await fetchText(
      `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`
    );
    let faces = parseFaces(css);
    const before = faces.length;

    if (fam.latinOnly) {
      faces = faces.filter((f) => f.range.includes(BASIC_LATIN));
    }

    // Stable local name per unique remote file, deduped across weights: a variable
    // font serves one file for every weight, so many faces share a URL.
    let idx = 0;
    const nameFor = new Map();
    for (const f of faces) {
      if (!nameFor.has(f.url)) {
        nameFor.set(f.url, `${fam.slug}-${fam.latinOnly ? 'latin' : idx++}.woff2`);
      }
    }

    /**
     * Inter and Noto Sans JP are variable fonts (wght axis), so Google emits one
     * block per requested weight all pointing at the SAME file. Collapse those into
     * a single rule with a weight range - 401 rules become 132, roughly a third of
     * the CSS. Reggae One is static and stays a single weight.
     */
    const groups = new Map();
    for (const f of faces) {
      const key = `${f.url}|${f.style}|${f.range}`;
      if (!groups.has(key)) groups.set(key, { ...f, weights: [] });
      groups.get(key).weights.push(Number(f.weight));
    }

    for (const g of groups.values()) {
      const local = nameFor.get(g.url);
      downloads.set(local, g.url);
      const lo = Math.min(...g.weights);
      const hi = Math.max(...g.weights);
      chunks.push(
        '@font-face {',
        `  font-family: '${g.family}';`,
        `  font-style: ${g.style};`,
        `  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};`,
        '  font-display: swap;',
        `  src: url('./fonts/${local}') format('woff2');`,
        `  unicode-range: ${g.range};`,
        '}',
        ''
      );
      totalFaces++;
    }

    console.log(
      `${fam.slug.padEnd(14)} ${String(faces.length).padStart(3)} faces` +
        ` -> ${String(groups.size).padStart(3)} rules` +
        ` / ${String(nameFor.size).padStart(3)} files` +
        (fam.latinOnly ? `  (filtered from ${before})` : '')
    );
  }

  // Download with bounded concurrency.
  const entries = [...downloads.entries()];
  let bytes = 0;
  const LIMIT = 8;
  for (let i = 0; i < entries.length; i += LIMIT) {
    await Promise.all(
      entries.slice(i, i + LIMIT).map(async ([local, url]) => {
        const res = await fetch(url, { headers: { 'User-Agent': UA } });
        if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
        const buf = Buffer.from(await res.arrayBuffer());
        bytes += buf.length;
        await writeFile(path.join(FONT_DIR, local), buf);
      })
    );
  }

  await writeFile(CSS_OUT, chunks.join('\n'), 'utf8');

  console.log(
    `\n${entries.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB` +
      `\n${totalFaces} @font-face rules -> src/styles/fonts.css`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
